[project]
name = "best-man"
version = "0.3.0"
requires-python = ">=3.8"
description="A mobile manipulator (with a wheel-base and arm) platform built on PyBullet simulation with unified hardware APIs."
readme = "README.md"

[project.urls]
reference = "https://api.semanticscholar.org/CorpusID:273403368"

[tool.black]
line-length = 79
exclude = '''
/(
    Asset
  | Config
  | Install
  | \.idea
  | \.vscode
  | \.git
)/
'''

[tool.isort]
profile = "black"
skip = ["Asset", "Config", "Install"]
